# Generated by Django 5.1.2 on 2024-10-12 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('personal-accident', 'Personal Accident'), ('health-insurance', 'Health Insurance'), ('life-insurance', 'Life Insurance'), ('home-insurance', 'Home Insurance'), ('auto-insurance', 'Auto Insurance')], max_length=50, unique=True)),
                ('premium', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('cover', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
