# Generated by Django 5.1.2 on 2024-10-12 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_app', '0004_quote_policyhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='buy_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
